### ISSUE TITLE
패키지 이름과 index.html 파일 이름을 소문자로 수정해주세요

### ISSUE THREAD

**Issue by sigmadream** [sbkim1126/ks-web#1]
https://github.com/sbkim1126/ks-web/blob/10ab1a34c8e7aca5e1781cc447f2de1bdd203efd/src/main/java/Controller/IndexController.java#L1

1) 패키지 이름, 2) index.html 파일 이름을 소문자로 수정해주세요

**Comment by sbkim1126** [comment]
앗 이슈 확인을 이제했습니다! 바로 수정해서 올렸는데 확인 부탁드립니다!!

**Comment by sigmadream** [comment]
수고하셨습니다.

**Comment by sbkim1126** [comment]
감사합니다!
